
mkdir DOWNLOAD_DELAY
mkdir ALL_APPS_GENERIC
mkdir UPLOAD_DELAY
mkdir INFOTAINMENT_GENERIC
mkdir DEVICES_LOCATION
mkdir DANGER_ASSESSMENT_GENERIC
mkdir TRAFFIC_MANAGEMENT_GENERIC
mkdir DEVICES_VM_LOAD

mv *DOWNLOAD_DELAY*.csv DOWNLOAD_DELAY
mv *ALL_APPS_GENERIC*.csv ALL_APPS_GENERIC 
mv *UPLOAD_DELAY*.csv UPLOAD_DELAY 
mv *INFOTAINMENT_GENERIC*.csv INFOTAINMENT_GENERIC
mv *DEVICES_LOCATION*.csv DEVICES_LOCATION
mv *DANGER_ASSESSMENT_GENERIC*.csv DANGER_ASSESSMENT_GENERIC
mv *TRAFFIC_MANAGEMENT_GENERIC*.csv TRAFFIC_MANAGEMENT_GENERIC 
mv *DEVICES_VM_LOAD*.csv DEVICES_VM_LOAD 
