mkdir AI_Based
mkdir MAB
mkdir Predictive
mkdir Random

mv *AI_BASED*.csv AI_Based
mv *MAB*.csv MAB
mv *PREDICTIVE*.csv Predictive
mv *RANDOM*.csv Random


cd AI_Based

mkdir DOWNLOAD_DELAY
mkdir ALL_APPS_GENERIC
mkdir UPLOAD_DELAY
mkdir INFOTAINMENT_GENERIC
mkdir DEVICES_LOCATION
mkdir DANGER_ASSESSMENT_GENERIC
mkdir TRAFFIC_MANAGEMENT_GENERIC
mkdir DEVICES_VM_LOAD
mkdir DEVICES_DRONES_LOCATIONS

mv *DOWNLOAD_DELAY*.csv DOWNLOAD_DELAY
mv *ALL_APPS_GENERIC*.csv ALL_APPS_GENERIC 
mv *UPLOAD_DELAY*.csv UPLOAD_DELAY 
mv *INFOTAINMENT_GENERIC*.csv INFOTAINMENT_GENERIC
mv *DEVICES_LOCATION*.csv DEVICES_LOCATION
mv *DANGER_ASSESSMENT_GENERIC*.csv DANGER_ASSESSMENT_GENERIC
mv *TRAFFIC_MANAGEMENT_GENERIC*.csv TRAFFIC_MANAGEMENT_GENERIC 
mv *DEVICES_VM_LOAD*.csv DEVICES_VM_LOAD 
mv *DEVICES_DRONES_LOCATIONS*.csv DEVICES_DRONES_LOCATIONS 


cd ALL_APPS_GENERIC/;
cat *.csv > ../ALL_APPS_GENERIC.csv;
cd ../DANGER_ASSESSMENT_GENERIC;
cat *.csv > ../DANGER_ASSESSMENT_GENERIC.csv;
cd ../DEVICES_LOCATION;
cat *.csv > ../DEVICES_LOCATION.csv;
cd ../DEVICES_VM_LOAD;
cat *.csv > ../DEVICES_VM_LOAD.csv;
cd ../DOWNLOAD_DELAY;
cat *.csv > ../DOWNLOAD_DELAY.csv;
cd ../INFOTAINMENT_GENERIC;
cat *.csv > ../INFOTAINMENT_GENERIC.csv;
cd ../TRAFFIC_MANAGEMENT_GENERIC;
cat *.csv > ../TRAFFIC_MANAGEMENT_GENERIC.csv;
cd ../UPLOAD_DELAY;
cat *.csv > ../UPLOAD_DELAY.csv;
cd ../DEVICES_DRONES_LOCATIONS;
cat *.csv > ../DEVICES_DRONES_LOCATIONS.csv;

cd ..
#=================================

cd ../MAB
mkdir DOWNLOAD_DELAY
mkdir ALL_APPS_GENERIC
mkdir UPLOAD_DELAY
mkdir INFOTAINMENT_GENERIC
mkdir DEVICES_LOCATION
mkdir DANGER_ASSESSMENT_GENERIC
mkdir TRAFFIC_MANAGEMENT_GENERIC
mkdir DEVICES_VM_LOAD
mkdir DEVICES_DRONES_LOCATIONS

mv *DOWNLOAD_DELAY*.csv DOWNLOAD_DELAY
mv *ALL_APPS_GENERIC*.csv ALL_APPS_GENERIC 
mv *UPLOAD_DELAY*.csv UPLOAD_DELAY 
mv *INFOTAINMENT_GENERIC*.csv INFOTAINMENT_GENERIC
mv *DEVICES_LOCATION*.csv DEVICES_LOCATION
mv *DANGER_ASSESSMENT_GENERIC*.csv DANGER_ASSESSMENT_GENERIC
mv *TRAFFIC_MANAGEMENT_GENERIC*.csv TRAFFIC_MANAGEMENT_GENERIC 
mv *DEVICES_VM_LOAD*.csv DEVICES_VM_LOAD 
mv *DEVICES_DRONES_LOCATIONS*.csv DEVICES_DRONES_LOCATIONS 


cd ALL_APPS_GENERIC/;
cat *.csv > ../ALL_APPS_GENERIC.csv;
cd ../DANGER_ASSESSMENT_GENERIC;
cat *.csv > ../DANGER_ASSESSMENT_GENERIC.csv;
cd ../DEVICES_LOCATION;
cat *.csv > ../DEVICES_LOCATION.csv;
cd ../DEVICES_VM_LOAD;
cat *.csv > ../DEVICES_VM_LOAD.csv;
cd ../DOWNLOAD_DELAY;
cat *.csv > ../DOWNLOAD_DELAY.csv;
cd ../INFOTAINMENT_GENERIC;
cat *.csv > ../INFOTAINMENT_GENERIC.csv;
cd ../TRAFFIC_MANAGEMENT_GENERIC;
cat *.csv > ../TRAFFIC_MANAGEMENT_GENERIC.csv;
cd ../UPLOAD_DELAY;
cat *.csv > ../UPLOAD_DELAY.csv;
cd ../DEVICES_DRONES_LOCATIONS;
cat *.csv > ../DEVICES_DRONES_LOCATIONS.csv;

cd ..
# ------------------------------------

cd ../Predictive

mkdir DOWNLOAD_DELAY
mkdir ALL_APPS_GENERIC
mkdir UPLOAD_DELAY
mkdir INFOTAINMENT_GENERIC
mkdir DEVICES_LOCATION
mkdir DANGER_ASSESSMENT_GENERIC
mkdir TRAFFIC_MANAGEMENT_GENERIC
mkdir DEVICES_VM_LOAD
mkdir DEVICES_DRONES_LOCATIONS

mv *DOWNLOAD_DELAY*.csv DOWNLOAD_DELAY
mv *ALL_APPS_GENERIC*.csv ALL_APPS_GENERIC 
mv *UPLOAD_DELAY*.csv UPLOAD_DELAY 
mv *INFOTAINMENT_GENERIC*.csv INFOTAINMENT_GENERIC
mv *DEVICES_LOCATION*.csv DEVICES_LOCATION
mv *DANGER_ASSESSMENT_GENERIC*.csv DANGER_ASSESSMENT_GENERIC
mv *TRAFFIC_MANAGEMENT_GENERIC*.csv TRAFFIC_MANAGEMENT_GENERIC 
mv *DEVICES_VM_LOAD*.csv DEVICES_VM_LOAD 
mv *DEVICES_DRONES_LOCATIONS*.csv DEVICES_DRONES_LOCATIONS 


cd ALL_APPS_GENERIC/;
cat *.csv > ../ALL_APPS_GENERIC.csv;
cd ../DANGER_ASSESSMENT_GENERIC;
cat *.csv > ../DANGER_ASSESSMENT_GENERIC.csv;
cd ../DEVICES_LOCATION;
cat *.csv > ../DEVICES_LOCATION.csv;
cd ../DEVICES_VM_LOAD;
cat *.csv > ../DEVICES_VM_LOAD.csv;
cd ../DOWNLOAD_DELAY;
cat *.csv > ../DOWNLOAD_DELAY.csv;
cd ../INFOTAINMENT_GENERIC;
cat *.csv > ../INFOTAINMENT_GENERIC.csv;
cd ../TRAFFIC_MANAGEMENT_GENERIC;
cat *.csv > ../TRAFFIC_MANAGEMENT_GENERIC.csv;
cd ../UPLOAD_DELAY;
cat *.csv > ../UPLOAD_DELAY.csv;
cd ../DEVICES_DRONES_LOCATIONS;
cat *.csv > ../DEVICES_DRONES_LOCATIONS.csv;

cd ..

#--------------------------------
cd ../Random

mkdir DOWNLOAD_DELAY
mkdir ALL_APPS_GENERIC
mkdir UPLOAD_DELAY
mkdir INFOTAINMENT_GENERIC
mkdir DEVICES_LOCATION
mkdir DANGER_ASSESSMENT_GENERIC
mkdir TRAFFIC_MANAGEMENT_GENERIC
mkdir DEVICES_VM_LOAD
mkdir DEVICES_DRONES_LOCATIONS

mv *DOWNLOAD_DELAY*.csv DOWNLOAD_DELAY
mv *ALL_APPS_GENERIC*.csv ALL_APPS_GENERIC 
mv *UPLOAD_DELAY*.csv UPLOAD_DELAY 
mv *INFOTAINMENT_GENERIC*.csv INFOTAINMENT_GENERIC
mv *DEVICES_LOCATION*.csv DEVICES_LOCATION
mv *DANGER_ASSESSMENT_GENERIC*.csv DANGER_ASSESSMENT_GENERIC
mv *TRAFFIC_MANAGEMENT_GENERIC*.csv TRAFFIC_MANAGEMENT_GENERIC 
mv *DEVICES_VM_LOAD*.csv DEVICES_VM_LOAD 
mv *DEVICES_DRONES_LOCATIONS*.csv DEVICES_DRONES_LOCATIONS 


cd ALL_APPS_GENERIC/;
cat *.csv > ../ALL_APPS_GENERIC.csv;
cd ../DANGER_ASSESSMENT_GENERIC;
cat *.csv > ../DANGER_ASSESSMENT_GENERIC.csv;
cd ../DEVICES_LOCATION;
cat *.csv > ../DEVICES_LOCATION.csv;
cd ../DEVICES_VM_LOAD;
cat *.csv > ../DEVICES_VM_LOAD.csv;
cd ../DOWNLOAD_DELAY;
cat *.csv > ../DOWNLOAD_DELAY.csv;
cd ../INFOTAINMENT_GENERIC;
cat *.csv > ../INFOTAINMENT_GENERIC.csv;
cd ../TRAFFIC_MANAGEMENT_GENERIC;
cat *.csv > ../TRAFFIC_MANAGEMENT_GENERIC.csv;
cd ../UPLOAD_DELAY;
cat *.csv > ../UPLOAD_DELAY.csv;
cd ../DEVICES_DRONES_LOCATIONS;
cat *.csv > ../DEVICES_DRONES_LOCATIONS.csv;

cd ..

